### ISSUE TITLE
Clojure module dependency capture and visualization in snapshots

### ISSUE THREAD

**Issue by grahambrooks** [kuona/kuona#3]
Maven projects currently display their dependencies as a chart or graph. This story extends this support by capturing clojure project dependencies.

A couple of options 

1. `lein deps :tree` produces a clojure style formatted tree of dependencies.
2. `lein pom` produces a pom that could then be processed by the current dependency reader.

**Comment by javatarz** [comment]
If I'm reading this correctly, we have a repo with multiple languages with multiple build tools. Isn't there a build tool that does a decent job across both (gradle?) If so, wouldn't we rather prefer to have 1 tool than two?

If the answer to that is no, I think the tools not being coupled would be a better option so I'd vote for `lein deps :tree` :)

**Comment by grahambrooks** [comment]
I am not aware of something that will resolve and list dependencies across build tools. Creating a pom from the lien project is tempting but adds a file to the repository. If that file has been committed to version control then we would have to clean up afterwards (not a bit issue).

The maven dependency reader can produce a 'dot' dependency graph which is relatively easy to parse. In general though I have am inclined to capture the dependencies as close to the expected build tool as possible - to avoid transitive dependency problems in the build chain.

A long way of saying I prefer `lean deps :tree` too.

**Comment by grahambrooks** [comment]
grade through gradle as a library and lein thought reading the edn now collected and displayed as a list
